clear_password(): appease -Werror=unused-variable
secret.c: In function ‘clear_password’:
secret.c:115:18: error: unused variable ‘removed’ [-Werror=unused-variable]
  115 |         gboolean removed = secret_password_clear_sync(&mcds_secret_schema,
      |                  ^~~~~~~
cc1: all warnings being treated as errors